CREATE TABLE "test" (
    a1 VARCHAR(64) ENCODE LZO,
    a2 VARCHAR(64) ENCODE LZO,
    a3 VARCHAR(64) ENCODE LZO,
    a4 VARCHAR(64) ENCODE LZO,
    a5 VARCHAR(64) ENCODE LZO,
    a6 VARCHAR(64) ENCODE LZO,
    a7 VARCHAR(64) ENCODE LZO
);
